### ISSUE TITLE
Cargo crates in warehouse can spawn items that aren't intended to be in-game

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1131]
As an example, in GameID bk84Xf, 'Gloves' were spawned which, as per what @Alberyk told me, were the 'parent/'group' gloves container, whatever you'd call it, that serves as the base for all gloves that are actually used in game. Said gloves had no sprite and I don't believe are actually usable.

**Comment by Alberyk** [comment]
Same with it spawning poster without any info/the structure outside any wall:

![](https://i.gyazo.com/c36de9700f9b65a0bad1221bed7e0d56.png)

**Comment by EvilBrage** [comment]
Not to mention it spawns traitor-only items such as the thermal imaging goggles which, I suspect, are not supposed to spawn.

**Comment by NanakoAC** [comment]
@EvilBrage not a bug.

**Comment by NanakoAC** [comment]
fixed in #1143

**Comment by skull132** [comment]
Not entirely fixed, the exclusion lists still need more shit.

Another entry: any type of HUD glasses, as they are not ID locked and can be easily abused.

**Comment by Arrow768** [comment]
Awaiting mere is to be used for pull requests that need merging.

**Comment by ShameOnTurtles** [comment]
Game ID bK7mYf saw the syndicate hardsuit control module spawn. Mentioning this for knowledge of what needs to be excluded purposes.

**Comment by Alberyk** [comment]
Things that are possible issues:
- augmentvision and thermals, both are pretty much thermal glasses.
- swords, they can block and deal around 40 of brute per hit
- ERT, crismon red hardsuit and stealth hardsuit.
- tacticool locker with swat armor

**Comment by Alberyk** [comment]
Cargo can also spawn adminordrazine chem cartridges.

**Comment by Serveris** [comment]
Cargo can spawn the Rapid Service Fabricator (RSF) device, which is a service cyborg loadout item.

**Comment by Serveris** [comment]
Cargo can spawn a circuitboard to Central Command ID Modification consoles.
