### ISSUE TITLE
[Newmap] Misc Issues 2

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2362]
Re-creation of old misc issues so these aren't forgotten.
~~* The Quartermaster's window tint does not work properly.~~
~~* The telecomms upper-level lounge does not appear to be connected to the grid.~~
~~* Engineering has a pipe painter instead of a floor painter.~~
~~* The CCIA (crescent) shuttle's station-side airlock controller does not work properly - inner door will not open.~~
~~* The ERT shuttle's station-side airlock is non-functional.~~
~~* Missing firedoor at (176, 118, 5).~~
~~* Missing firedoor at (179, 116, 5).~~
~~* Missing firedoor at (175, 116, 5).~~
~~* The Materials lab in Research's APC is not connected to the grid.
![2017-05-06_20-47-06](https://cloud.githubusercontent.com/assets/7097800/25777256/47762a5a-329d-11e7-81b8-16a2ab5bd772.png)~~
~~* The cargo bay on the surface level does not have an APC.~~
~~* Window at (178, 125, 4) has no hazard shutter.~~
~~* Random windows at (167, 131, 6)~~
~~* The O2 tank in the telecomms control room is empty.~~

**Comment by Juani2400** [comment]
I fixed a few of these already, so they should be no longer an issue. Did you confirm all of these are still bugs?

**Comment by Lohikar** [comment]
Which ones did you fix? I tested most of these recently and they were still present.

**Comment by Juani2400** [comment]
#2438 fixes the following:
>
- The telecomms upper-level lounge does not appear to be connected to the grid.
- Engineering has a pipe painter instead of a floor painter.
- Missing firedoor at (176, 118, 5). (Wasn't missing one, but there were 2 on the same spot.)
- Missing firedoor at (179, 116, 5). (Wasn't missing one, but there were 2 on the same spot.)
- Missing firedoor at (175, 116, 5). (Wasn't missing one, but there were 2 on the same spot.)
- The Materials lab in Research's APC is not connected to the grid.
- The cargo bay on the surface level does not have an APC. (I think this was fixed before.)
- Window at (178, 125, 4) has no hazard shutter.
- Random windows at (167, 131, 6)
